service: availsmuch

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  environment:
    PRAYER_TABLE: "availsmuch-prayer-${opt:stage, self:provider.stage}"
    USER_TABLE: "availsmuch-user-${opt:stage, self:provider.stage}"
    NOTIFICATION_TABLE: "availsmuch-notification-${opt:stage, self:provider.stage}"
    GROUP_TABLE: "availsmuch-groups-${opt:stage, self:provider.stage}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"
    
functions:
  prayerRequests:
    handler: requests/request.router
    events:
      - http:
          path: requests
          method: any
          cors: true
      - http:
          path: requests/{id}
          method: any
          cors: true

  groups:
    handler: group/group.router
    events:
      - http:
          path: groups
          method: any
          cors: true
      - http:
          path: groups/{id}
          method: any
          cors: true

  createUser:
    handler: users/create.create
    events:
      - http:
          path: users
          method: post
          cors: true

  listUsers:
    handler: users/list.list
    events:
      - http:
          path: users
          method: get
          cors: true

  getUser:
    handler: users/get.get
    events:
      - http:
          path: users/{id}
          method: get
          cors: true

  updateUser:
    handler: users/update.update
    events:
      - http:
          path: users/{id}
          method: put
          cors: true

  deleteUser:
    handler: users/delete.delete
    events:
      - http:
          path: users/{id}
          method: delete
          cors: true

resources:
  Resources:
    prayerDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.PRAYER_TABLE}
    userDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.USER_TABLE}
